### ISSUE TITLE
java.io.IOException: Insufficient byte length[50331667] when io closed

### ISSUE THREAD

**Issue by liming1010** [Pluto-Whong/natcross2#10]
clientApp被我用在了android上面，app启动之后出错：
`I/System.out: 10:05:41.339 [main      ] [p.p.n.c.a.InteractiveSimpleClientAdapter     ] [ERROR] [100 ] - 向服务端[222.240.223.84:6000]建立控制通道失败`

服务端错误：
`09:55:56.273 [pool-2-thread-4] [p.p.n.s.c.a.ReadAheadPassValueAdapter        ] [ERROR] [57  ] - 读取数据异常
java.io.IOException: Insufficient byte length[50331667] when io closed
        at person.pluto.natcross2.channel.LengthChannel.read(LengthChannel.java:71)
        at person.pluto.natcross2.channel.StringChannel.read(StringChannel.java:35)
        at person.pluto.natcross2.channel.JsonChannel.read(JsonChannel.java:37)
        at person.pluto.natcross2.channel.InteractiveChannel.read(InteractiveChannel.java:37)
        at person.pluto.natcross2.channel.InteractiveChannel.read(InteractiveChannel.java:20)
        at person.pluto.natcross2.serverside.client.adapter.ReadAheadPassValueAdapter.procMethod(ReadAheadPassValueAdapter.java:54)
        at person.pluto.natcross2.serverside.client.ClientServiceThread.lambda$procMethod$0(ClientServiceThread.java:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
09:55:56.288 [pool-2-thread-4] [p.p.n.s.client.ClientServiceThread           ] [ERROR] [89  ] - 处理socket异常
java.io.IOException: Insufficient byte length[50331667] when io closed
        at person.pluto.natcross2.channel.LengthChannel.read(LengthChannel.java:71)
        at person.pluto.natcross2.channel.StringChannel.read(StringChannel.java:35)
        at person.pluto.natcross2.channel.JsonChannel.read(JsonChannel.java:37)
        at person.pluto.natcross2.channel.InteractiveChannel.read(InteractiveChannel.java:37)
        at person.pluto.natcross2.channel.InteractiveChannel.read(InteractiveChannel.java:20)
        at person.pluto.natcross2.serverside.client.adapter.ReadAheadPassValueAdapter.procMethod(ReadAheadPassValueAdapter.java:54)
        at person.pluto.natcross2.serverside.client.ClientServiceThread.lambda$procMethod$0(ClientServiceThread.java:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
09:56:00.616 [pool-3-thread-1] [p.p.n.s.listen.ServerListenThread            ] [DEBUG] [297 ] - clearInvaildSocketPart[7000]`

要怎么才能在android上面呢

**Comment by Pluto-Whong** [comment]
这种报错一般是控制端口和鉴定端口配置错误的问题，一般 CommonConstants 中 servicePort 不需要改动，重要的是 listenDestArray 中的端口对
