### ISSUE TITLE
客户端启动报错

### ISSUE THREAD

**Issue by longan-wang** [Pluto-Whong/natcross2#11]
os：centos7
jre：17

[root@localhost nat-client]# /usr/bin/jre-17/bin/java -jar ./ClientApp.jar
Exception in thread "main" java.io.IOException: Insufficient byte length[4] when io closed
	at person.pluto.natcross2.channel.LengthChannel.read(LengthChannel.java:59)
	at person.pluto.natcross2.channel.StringChannel.read(StringChannel.java:35)
	at person.pluto.natcross2.channel.JsonChannel.read(JsonChannel.java:37)
	at person.pluto.natcross2.channel.SecretInteractiveChannel.read(SecretInteractiveChannel.java:61)
	at person.pluto.natcross2.channel.SecretInteractiveChannel.read(SecretInteractiveChannel.java:29)
	at person.pluto.natcross2.clientside.adapter.InteractiveSimpleClientAdapter.createControlChannel(InteractiveSimpleClientAdapter.java:109)
	at person.pluto.natcross2.clientside.ClientControlThread.createControl(ClientControlThread.java:59)
	at person.pluto.natcross2.ClientApp.secret(ClientApp.java:112)
	at person.pluto.natcross2.ClientApp.main(ClientApp.java:27)

**Comment by longan-wang** [comment]
已经解决了，是因为服务端和客户端所在的机器的操作系统时间存在时间差且时间差>5秒导致的，客户端在向服务端发起连接时，服务端会校验时间，如果大于5秒将校验失败，客户端会连接失败。
解决办法1：同步两台机器的系统时间
解决办法2：将overtimeMills超时时间修改大一些，或者将这个校验注释掉，就可以了
![image](https://github.com/Pluto-Whong/natcross2/assets/20065793/4af0512a-188c-4b5a-b687-ef1fd3893712)
